{% set version = "5.9.0" %}
{% set ver = '.'.join(version.split('.')[:2]) %}

package:
  name: qtwebkit
  version: {{ version }}

source:
  - url: http://download.qt.io/community_releases/{{ ver }}/{{ version }}-final/qtwebkit-opensource-src-{{ version }}.tar.xz  # [not win]
    sha256: 8dad193b740055a998312e04a040f2e32a923c0823b2d239b24eab08276a4e04  # [not win]
  - url: https://github.com/qt/qtwebkit/archive/v5.212.0-alpha2.zip  # [win]
    fn: qtwebkit-opensource-src-{{ version }}-v5.212.0-alpha2.zip
    sha256: f2598a511c4e240f0b005c0aac44e40e17244bb3b0f19cbab1a77bf0ec38183a  # [win]
    patches:
      # ICU paths are incomplete (needs reported; though probably works with non-VS CMake generators)
      - 0000-options-qt-full-icu-paths.patch
      # When crosscompiling on Win 7 with VS2017, but using VS2015, `cmake --system-information`
      # forces v141 instead of v140 since it uses VS2017, by default.
      # This causes MSBuild to not find the platform targets, then error.
      - 0001-webkitdirs-hardcode-64-bit.patch

build:
  number: 0
  skip: True  # [win and vc != 14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bison             # [not win]
    - flex              # [not win]
    - m4                # [not win]
    - m2-bison          # [win]
    - m2-flex           # [win]
    - m2-gperf          # [win]
    - m2-grep           # [win]
    - m2-m4             # [win]
    - cmake             # [win]
    - perl 5.*          # [win]
    - python 2.7*       # [win]
    - ninja             # [win]
  host:
    - qt {{ ver }}.*
    - icu               # [win]
    - freetype          # [win]
    - fontconfig        # [win]
    - jpeg              # [win]
    - libiconv          # [win]
    - libpng            # [win]
    - libxml2           # [win]
    - libxslt           # [win]
    - libwebp           # [win]
    - sqlite            # [win]
    - zlib              # [win]
  run:
    - qt {{ ver }}.*

test:
  commands:
    - test -f $PREFIX/lib/libQt5WebKit.dylib  # [osx]
    - test -f $PREFIX/lib/libQt5WebKit.lib  # [win]
    - test -f $PREFIX/bin/Qt5WebKit.dll  # [win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://wiki.qt.io/Qt_WebKit
  license: GPL-3.0
  license_file: LICENSE.GPLv3
  summary: 'WebKit is one of the major engine to render webpages and execute JavaScript code'
  description: |
    Qt WebKit is the port of WebKit on top of Qt. QtWebKit relies on the public APIs of Qt
    and can theoretically be used on any platform supported by Qt
    (theoretically because WebKit also requires a recent/good compiler).

extra:
  recipe-maintainers:
    - ceholden
    - dakcarto
    - gillins
    - mingwandroid
    - ocefpaf
