{% set version = "5.9.0" %}
{% set ver = '.'.join(version.split('.')[:2]) %}

package:
  name: qtwebkit
  version: {{ version }}

source:
  # TODO: see if 5.212 should be the src for *nix
  - url: http://download.qt.io/community_releases/{{ ver }}/{{ version }}-final/qtwebkit-opensource-src-{{ version }}.tar.xz  # [not win]
    sha256: 8dad193b740055a998312e04a040f2e32a923c0823b2d239b24eab08276a4e04  # [not win]
  - url: https://github.com/qt/qtwebkit/archive/v5.212.0-alpha4.zip  # [win]
    fn: qtwebkit-opensource-src-{{ version }}-v5.212.0-alpha4.zip
    sha256: 4076bfa20e00feede3d228663719fb1b5645e00b602fc804f902cc047cd8f927  # [win]
    patches:
      # ICU paths are incomplete (needs reported; though probably works with non-VS CMake generators)
      #- 0000-options-qt-full-icu-paths.patch  # [win]
      # When crosscompiling on Win 7 with VS2017, but using VS2015, `cmake --system-information`
      # forces v141 instead of v140 since it uses VS2017, by default.
      # This causes MSBuild to not find the platform targets, then error.
      #- 0001-webkitdirs-hardcode-64-bit.patch  # [win]

build:
  number: 0
  skip: True  # [win and vc != 14]
  detect_binary_files_with_prefix: true
  script_env:
    - PYTHON

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bison             # [not win]
    - flex              # [not win]
    - m4                # [not win]
    - python 3.*        # [win]
    - cmake             # [win]
    - conan             # [win]
    - ninja             # [win]
  host:
    # qtwebkit needs to be used against the same version of Qt that
    # it was released for.
    - qt {{ ver }}.*
    - icu               # [win]
    - jpeg              # [win]
    - libiconv          # [win]
    - libpng            # [win]
    - libxml2           # [win]
    - libxslt           # [win]
    - libwebp           # [win]
    - sqlite            # [win]
    - zlib              # [win]
  run:
    - qt {{ ver }}.*
    - python 3.*

test:
  commands:
    - test -f $PREFIX/lib/libQt5WebKit.dylib  # [osx]
    - if not exist %LIBRARY_LIB%\Qt5WebKit.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\Qt5WebKit.dll exit 1  # [win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://wiki.qt.io/Qt_WebKit
  license: LGPL-2.1
  license_file: LICENSE.LGPLv21
  summary: 'WebKit is one of the major engine to render webpages and execute JavaScript code'
  description: |
    Qt WebKit is the port of WebKit on top of Qt. QtWebKit relies on the public APIs of Qt
    and can theoretically be used on any platform supported by Qt
    (theoretically because WebKit also requires a recent/good compiler).

extra:
  recipe-maintainers:
    - ceholden
    - dakcarto
    - gillins
    - mingwandroid
    - ocefpaf
